// Standard-library-only standalone build. Never changes an existing release.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const bank=JSON.parse(read('study/bank.json'));
const weekMapping=JSON.parse(read('study/week-mapping.json'));
const release=JSON.parse(read('study/release.json'));
assert.equal(bank.version,'exam2-complete-1.1.1');
assert.equal(bank.questions.length,349);
assert.equal(release.version,bank.version);
assert.equal(release.bankSha256,sha(read('study/bank.json')),'Unapproved bank change');
assert.equal(release.hard80Enabled,true);
assert.equal(release.hard80Questions,80);
assert.equal(release.legacyMigration,false);
assert.equal(release.weekMappingVersion,weekMapping.mappingVersion);
assert.equal(release.weekMappingSha256,sha(read('study/week-mapping.json')),'Unapproved week mapping change');
assert.equal(weekMapping.bankCoverage.bankSha256,release.bankSha256);
const preserved=['index.html','data/bank.json','data/legacy-bank-v2.json','checkpoint/bank.json','checkpoint/engine.mjs','checkpoint/app.mjs'];
const before=Object.fromEntries(preserved.map(file=>[file,sha(read(file))]));
for(const file of preserved)assert.equal(before[file],release.preserved[file],'Legacy artifact changed: '+file);
const stripImports=source=>source.replace(/^import[\s\S]*?from ['"][^'"]+['"](?: with \{[^}]+\})?;\n/gm,'');
const selector=stripImports(read('study/hard80-selector.mjs')).replace(/^export /gm,'');
const mappingRuntime=stripImports(read('study/week-mapping.mjs')).replace(/^export /gm,'');
const engine=stripImports(read('study/engine.mjs')).replace(/^export /gm,'');
const hard80=stripImports(read('study/hard80.mjs')).replace(/^export /gm,'');
const app=stripImports(read('study/app.mjs'));
const js=selector+'\nconst weekMapping='+JSON.stringify(weekMapping).replace(/</g,'\\u003c')+';\n'+mappingRuntime+'\n'+engine+'\n'+hard80+'\nconst bank='+JSON.stringify(bank).replace(/</g,'\\u003c')+';\n'+app;
new vm.Script(js);
const svg=read('study/icons/favicon.svg');
const svgUrl='data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64');
const html='<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#09695f"><meta name="description" content="349 NUR2460 Exam 2 questions with week-filtered adaptive Study and a separate full Hard 80 exam. Fresh isolated progress; earlier versions preserved."><title>NUR2460 · Exam 2 Complete</title><link rel="icon" type="image/svg+xml" href="icons/favicon.svg"><link rel="icon" href="icons/favicon.ico" sizes="any"><link rel="apple-touch-icon" href="icons/apple-touch-icon.png"><style>'+read('study/styles.css')+'</style></head><body><div id="app"></div><noscript>This interactive learning tool requires JavaScript. Your earlier quiz and progress remain available in their original versions.</noscript><script>'+js.replace('src="icons/favicon.svg"','src="'+svgUrl+'"').replace(/<\/script/gi,'<\\/script')+'</script></body></html>\n';
for(const pattern of [/\/Users\//,/\.study-build\//,/reviews\/(?:parallel|release)/,/file:\/\//,/gh[opsu]_[A-Za-z0-9]{16}/,/localhost:\d+/])assert(!pattern.test(html),'Private detail in public HTML: '+pattern);
assert(!/<script[^>]+src=|<link[^>]+rel=["']stylesheet|@import\s/i.test(html),'Unexpected external runtime dependency');
assert(!/localStorage\.(?:getItem|setItem|removeItem)\(["']nur2460-(?:exam2|study-checkpoint|study-first)/.test(html),'Legacy storage access');
assert(!/^import |^export /m.test(js),'Unbundled module');
const out=path.join(root,'dist/study');fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'index.html'),html);
const assets={};for(const file of ['favicon.svg','favicon.ico','apple-touch-icon.png'])assets[file]=sha(fs.readFileSync(path.join(root,'study/icons',file)));
const artifact={...release,htmlSha256:sha(html),assets,weekMappingRuntimeSha256:sha(read('study/week-mapping.mjs')),runtimeSha256:sha(read('study/engine.mjs')),hard80RuntimeSha256:sha(read('study/hard80.mjs')),selectorSha256:sha(read('study/hard80-selector.mjs')),uiSha256:sha(read('study/app.mjs')),stylesSha256:sha(read('study/styles.css'))};
fs.writeFileSync(path.join(out,'release.json'),JSON.stringify(artifact,null,2)+'\n');
fs.cpSync(path.join(root,'study/icons'),path.join(out,'icons'),{recursive:true});
for(const file of preserved)assert.equal(sha(read(file)),before[file],'Build changed legacy file: '+file);
console.log(JSON.stringify({version:bank.version,questions:bank.questions.length,htmlBytes:Buffer.byteLength(html),htmlSha256:sha(html),legacyArtifactsUnchanged:true,output:'dist/study/index.html'},null,2));
